### PR TITLE
[pm-5966] Fix Entity Framework query for MySQL

### LINKED ISSUE #3722: Organization domain maintenance failed because of untranslated query
### Steps To Reproduce

1. Deploy docker/self-host:[v2024.1.2](https://hub.docker.com/layers/bitwarden/self-host/2024.1.2-beta/images/sha256-10ccff66668ef6c40c7dbb53b9e12145dadbbb349d17bbf0e56067fe20b74802?context=explore)
2. Create organization with user (maybe not required - unsure)

Other steps may be required, but I am unsure how to trigger Organization Domain Maintenance.

### Expected Result

No errors in admin.log

### Actual Result

Error in admin.log:
```c#
fail: Bit.Core.Services.OrganizationDomainService[0]
      Organization domain maintenance failed
      System.InvalidOperationException: The LINQ expression 'DbSet<OrganizationDomain>()
          .Where(o => (DateTime.UtcNow - o.CreationDate).Days == 4 && o.VerifiedDate == null)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
         at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
         at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
         at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
         at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
         at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
         at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Bit.Infrastructure.EntityFramework.Repositories.OrganizationDomainRepository.GetExpiredOrganizationDomainsAsync() in /source/src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs:line 126
         at Bit.Core.Services.OrganizationDomainService.OrganizationDomainMaintenanceAsync() in /source/src/Core/Services/Implementations/OrganizationDomainService.cs:line 101
```

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Githash Version

dca8d00

### Environment Details

Docker

### Database Image

mariadb:11

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by JimmyVo16**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-5966

## 📔 Objective

Problem: The Entity Framework query was causing a compile-time error.

Changes:

1. Fixed the query.
2. Renamed the variable to replace the comment.

## 📸 Screenshots

Manual testing 

Generated SQL query.
image

With results

image

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

File: src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs [hunk 1]
```diff
@@ -147,14 +147,13 @@ from s in sJoin.DefaultIfEmpty()
         using var scope = ServiceScopeFactory.CreateScope();
         var dbContext = GetDatabaseContext(scope);
 
-        //Get domains that have not been verified after 72 hours
-        var domains = await dbContext.OrganizationDomains
-            .Where(x => (DateTime.UtcNow - x.CreationDate).Days == 4
-                        && x.VerifiedDate == null)
+        var unverifiedDomainsInLast72Hours = await dbContext.OrganizationDomains
+            .Where(x => x.CreationDate.Date >= DateTime.UtcNow.AddDays(-4).Date
```
Comment (JimmyVo16) [inline src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs:151]: Question: I'm not sure if a unit test would add value here since the behavior can only be tested at runtime.

Comment (r-tome) [reply src/Infrastructure.EntityFramework/Repositories/OrganizationDomainRepository.cs:151]: You can add an integration test on the project `Infrastructure.IntegrationTest` using the `DatabaseData` attribute which configures the test to run once for each configured DB provider.
Example here https://github.com/bitwarden/server/blob/main/test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationRepositoryTests.cs

**Review by r-tome — CHANGES_REQUESTED** [review]
It looks good to me but it would be ideal to have the integration test

**Comment by holow29** [comment]
Looks like this should resolve #3722.  Funny to see it resolved because of a compilation issue vs. the pre-existing issue.

File: test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationDomainRepositoryTests.cs [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+using Bit.Infrastructure.EntityFramework.AdminConsole.Models;
+using Bit.Infrastructure.EntityFramework.Models;
+using Xunit;
+
+namespace Bit.Infrastructure.IntegrationTest.Repositories;
+
+public class OrganizationDomainRepositoryTests
+{
+    [DatabaseTheory, DatabaseData]
+    public async Task GetExpiredOrganizationDomainsAsync_ShouldReturnExpiredOrganizationDomains(
```
Comment (JimmyVo16) [inline test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationDomainRepositoryTests.cs:12]: hey @eliykat 

I’m trying to add a test for the VerifiedDate field, and I need a way to update it. My plan is to create a class that extends OrganizationDomain and add test logic to update the VerifiedDate, since this will only be used in test env. 

Just wanted to check if this is an acceptable pattern here or if there’s a better way to handle this.

Comment (r-tome) [reply test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationDomainRepositoryTests.cs:12]: Which specific test are you trying to add? It looks like you're already using the `.SetVerifiedDate()` method here, and it seems to be fulfilling the purpose for these tests.

Comment (r-tome) [reply test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationDomainRepositoryTests.cs:12]: Maybe you meant `CreationDate`? Well, that one seems tricky. Maybe you can use `ITimeProvider` to set the value and then mock it on the test?

Comment (JimmyVo16) [reply test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationDomainRepositoryTests.cs:12]: Sorry, I meant `CreationDate`. Thanks, I'll look into `ITimeProvider`.

Comment (JimmyVo16) [reply test/Infrastructure.IntegrationTest/AdminConsole/Repositories/OrganizationDomainRepositoryTests.cs:12]: After a nice weekend of rest, this is actually easier than I thought, lol. I added the new tests.

**Review by r-tome — DISMISSED** [review]

**Review by r-tome — APPROVED** [review]
