### PR TITLE
Use UrlB64 encoding for auth-email header

### LINKED ISSUE #1502: Unable to log in using email address with accented character
## Describe the Bug

I received an error "An error has occurred." when I tried to log in to my account.
The email address contains accented characters.

## Expected Result

Able to log in normally.

## Actual Result

Unable to log in.

### PR DESCRIPTION
**Pull request by eliykat**
## Objective

Fix #1502. Our identity middleware throws an exception if there are unicode characters in request headers. In #1361 we added the user's email address in the request headers, which can contain unicode characters.

This solution proposes using Base64Url encoding for the `auth-email` header.

## Code changes
* refactor: move the `auth-email` validation logic into its own method
* decode from Base64Url before validating `auth-email`.

## Other repos
* jslib: https://github.com/bitwarden/jslib/pull/450
* mobile: I will submit a PR for this once I have confirmation that this is the correct approach

### CODE REVIEW

File: src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs [hunk 1]
```diff
@@ -135,5 +134,33 @@ protected async override Task<(User, bool)> ValidateContextAsync(ResourceOwnerPa
...
+            else
+            {
+                try
+                {
+                    var authEmailHeader = _currentContext.HttpContext.Request.Headers["Auth-Email"];
+                    var authEmailDecoded = CoreHelpers.Base64UrlDecodeString(authEmailHeader);
+
+                    if (authEmailDecoded != context.UserName)
+                    {
+                        return false;
```
Comment (cscharf) [inline src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:153]: This is okay for this fix, however the preference for a simple boolean return would be something like this for simplification (without the `if` statement):

```c#
return authEmailDecoded == context.UserName;
```

File: src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs [hunk 2]
```diff
@@ -135,5 +134,33 @@ protected async override Task<(User, bool)> ValidateContextAsync(ResourceOwnerPa
...
+                    }
+                }
+                catch (System.Exception e) when (e is System.InvalidOperationException || e is System.FormatException)
+                {
+                    // Invalid B64 encoding
+                    return false;
+                }
+            }
+
+            return true;
```
Comment (cscharf) [inline src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:163]: This could then be removed if using the prior suggestion, further simplifying the flow.

**Review by cscharf — APPROVED** [review]

File: src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs [hunk 3]
```diff
@@ -135,5 +134,33 @@ protected async override Task<(User, bool)> ValidateContextAsync(ResourceOwnerPa
...
+
+                    if (authEmailDecoded != context.UserName)
+                    {
+                        return false;
+                    }
+                }
+                catch (System.Exception e) when (e is System.InvalidOperationException || e is System.FormatException)
+                {
+                    // Invalid B64 encoding
+                    return false;
```
Comment (cscharf) [inline src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:159]: Actually, after thinking through reverse compatibility for old clients, new server scenarios, we absolutely need to have a fallback check here to check if the original/old logic holds true:

```c#
return _currentContext.HttpContext.Request.Headers["Auth-Email"] == context.UserName;
```

**Review by cscharf — CHANGES_REQUESTED** [review]

File: src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs (hunk 3 above)
Comment (cscharf) [reply src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:159]: Never mind @eliykat , that's my bad, this method currently is not called since it's invocation is commented out, duh, it's early in the AM for me still, no coffee yet 😉

**Review by cscharf — APPROVED** [review]

File: src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs (hunk 1 above)
Comment (eliykat) [reply src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs:153]: I did wonder about this but decided against it - will know for next time! Thanks
