### PR TITLE
Fix conflicting group permissions

### LINKED ISSUE #1450: Conflicting group-level permissions are prioritized based on alphabetical order
## Describe the Bug
If a user is assigned to multiple groups with contradicting permissions (read-only vs. read-write), the group that comes first alphabetically gets precedence. 

## Steps To Reproduce

1. Create a group named "Group1". 
2. Assign read-only permissions to a collection with that group.
3. Create another group named "Group2".
4. Assign read-write permissions to the same collection with that group.
5. Assign a user to Group1 and Group2.
6. Attempt to create a new item in the collection as the user. It will fail.

## Expected Result

Permissions should be unified in such a way that would allow users in Group1 (read-only) and Group2 (read-write) to write. Users granted a higher level of access by a group should not be limited by another group that comes first alphabetically.

## Actual Result

A user assigned to multiple groups will inherit the permissions from the first group in alphabetical order. 

## Environment

- Operating system: Cloud
- Build Version: 1.41.5
- Self Hosted: false
- Environment: Cloud

### PR DESCRIPTION
**Pull request by eliykat**
## Objective

Fix #1450:

> If a user is assigned to multiple groups with contradicting permissions (read-only vs. read-write), the group that comes first alphabetically gets precedence.

The problem is that `collectionRepository.GetManyByUserIdAsync` gets all relevant `collectionDetails` matching an id, but then just takes the first one without doing any reconciliation of permission levels.

## Code changes

Update `collectionRepository.GetManyByUserIdAsync` so that after getting the first `collectionDetails` result, it reconciles its permissions with the other results and returns a modified object with the highest permissions available to the user. This fixes the defect.

## Other changes

I also considered whether this change needed to be made anywhere else. The only other repository methods returning a `collectionDetails` object are `GetByIdAsync` and `GetByIdWithGroupsAsync`, which both rely on the `Collection_ReadyByIdUserId` SQL procedure. That SQL procedure returns the top result after sorting by `ReadOnly` ascending, ensuring that it'll always get the row with the highest `ReadOnly` permission. However, that may not be the row with the highest `HidePasswords` permission - so in theory it could have a similar problem. 

That said, I haven't tried to fix this for now because it's not actually causing any problems in practice, so I wasn't sure whether changing the SQL procedure would be messing with things unnecessarily. I could also be misunderstanding the intended return value. Whoever does code review - let me know if you think I should change this while I'm here.

### CODE REVIEW

**Review by addisonbeck — COMMENTED** [review]
Please also take a look at this in the Entity Framework implementation of the [method](https://github.com/bitwarden/server/blob/2419bc29281730c750f4f985dc0ea676c2fc6846/src/Core/Repositories/EntityFramework/CollectionRepository.cs#L136-L145).

File: src/Core/Repositories/SqlServer/CollectionRepository.cs [hunk 1]
```diff
@@ -107,7 +107,21 @@ public async Task<ICollection<CollectionDetails>> GetManyByUserIdAsync(Guid user
...
+                        {
+                            first.HidePasswords = !grouping.Any(c => !c.HidePasswords);
+                        }
+
+                        if (first.ReadOnly)
+                        {
+                            first.ReadOnly = !grouping.Any(c => !c.ReadOnly);
+                        }
+                        
+                        return first;
```
Comment (addisonbeck) [inline src/Core/Repositories/SqlServer/CollectionRepository.cs:123]: This kind of filtering logic (even though some of it already existed here) seems out of place in the repository. It doesn't seem like a huge life to move this logic into `Collection_ReadByUserId.sql`. Maybe we could improve that while in the area and relocate this?

**Comment by eliykat** [comment]
@addisonbeck This is now ready for review:
* SQL: no changes since our conversation in Slack, I double checked the query statements and I think they are both different and return the intended values.
* EF: I also lifted the filtering logic out of the repository and created new query classes for it. However, if I'm understanding things correctly, they'll be executed as normal LINQ statements by the program and not as queries by the database. I'm not sure if this is OK in the EF context or whether we need to push it down lower.

**Review by cscharf — APPROVED** [review]
These group by statement updates will get the appropriate aggregate permission/s, however we need to watch for index utilization and performance once they go live in production as that can have a huge negative impact (but need to find query plans before tuning).
