### PR TITLE
[PS-2363] fix bumping `AccountRevisionDate` when creating and updating ciphers

### LINKED ISSUE #2615: account revision date not bumped with EntityFramework DBs
### Steps To Reproduce

1. setup the mariadb sample
2. connect a desktop client and an android client
3. create a new password(cipher) using desktop

### Expected Result

Android will see the new entry. If not automatically it should at least show up after a manual sync.

### Actual Result

The entry will not show up until logging out and back in again. A manual sync doesn't help.

### Screenshots or Videos

_No response_

### Additional Context

I took look at the communication using tcpdump+wireshark and it looks like the only thing Android ever does is poll `GET /accounts/revision-date`.
That date does not change after creating a new password though.

I assume that unlike desktop, Android uses the date exclusively to decide if a sync is needed. So since that's never being updated by the server you'll never see any updates until you log out and back in again.

### Githash Version

3997defe-dirty

### Environment Details

- Operating System: Fedora CoreOS
- Container runtime: podman
- Hardware: RK3399 SBC (arm64)

mariadb container: https://github.com/M1cha/homeserver/blob/284054030b76e8faf4a3b5749e491157b6623c55/files/containers/bitwarden-mariadb.container
bitwarden container: https://github.com/M1cha/homeserver/blob/284054030b76e8faf4a3b5749e491157b6623c55/files/containers/bitwarden.container

### Database Image

docker.io/mariadb:10

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by M1cha**
When the user is not part of an organization,
`UserBumpAccountRevisionDateByCipherIdQuery` doesn't work. In that case we have to use `UserBumpAccountRevisionDateAsync` instead.

This was already done by most parts of the code but a few more were missing.

## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Fixes #2615

### CODE REVIEW

File: src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs [hunk 1]
```diff
@@ -107,7 +107,16 @@ private async Task<CipherDetails> CreateAsyncReturnCipher(CipherDetails cipher)
                 null;
             var entity = Mapper.Map<Cipher>((Core.Entities.Cipher)cipher);
             await dbContext.AddAsync(entity);
-            await dbContext.UserBumpAccountRevisionDateByCipherIdAsync(cipher.Id, cipher.OrganizationId.GetValueOrDefault());
```
Comment (justindbaur) [inline src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs:110]: I think we should probably also make this method not allow a nullable (`Guid?`) organization Id so that this mistake is harder to make in the future. This would require us to make this be non-nullable as well but that is in line with what the SQL Server implementation is so I think it's fine. 
https://github.com/bitwarden/server/blob/522df6e91a937e02fba018a0276bb1561fd40e3d/src/Infrastructure.EntityFramework/Repositories/Queries/UserBumpAccountRevisionDateByCipherIdQuery.cs#L10

We should also get rid of this constructor that looks like it's only used in one test so that is fine with me. 
https://github.com/bitwarden/server/blob/522df6e91a937e02fba018a0276bb1561fd40e3d/src/Infrastructure.EntityFramework/Repositories/Queries/UserBumpAccountRevisionDateByCipherIdQuery.cs#L12-L16

File: src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs [hunk 2]
```diff
@@ -107,7 +107,16 @@ private async Task<CipherDetails> CreateAsyncReturnCipher(CipherDetails cipher)
...
+
+            if (cipher.OrganizationId.HasValue)
+            {
+                await dbContext.UserBumpAccountRevisionDateByCipherIdAsync(cipher.Id, cipher.OrganizationId);
```
Comment (justindbaur) [inline src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs:113]: This would become:
```C#
await dbContext.UserBumpAccountRevisionDateByCipherIdAsync(cipher.Id, cipher.OrganizationId.Value);
```

File: src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs [hunk 3]
```diff
@@ -458,7 +467,16 @@ public async Task ReplaceAsync(CipherDetails cipher)
                 }
                 var mappedEntity = Mapper.Map<Cipher>((Core.Entities.Cipher)cipher);
                 dbContext.Entry(entity).CurrentValues.SetValues(mappedEntity);
-                await dbContext.UserBumpAccountRevisionDateByCipherIdAsync(cipher.Id, cipher.OrganizationId.GetValueOrDefault());
+
+                if (cipher.OrganizationId.HasValue)
+                {
+                    await dbContext.UserBumpAccountRevisionDateByCipherIdAsync(cipher.Id, cipher.OrganizationId);
```
Comment (justindbaur) [inline src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs:473]: Same here `.Value`

File: src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs [hunk 4]
```diff
@@ -566,7 +584,15 @@ public async Task<bool> ReplaceAsync(Core.Entities.Cipher cipher, IEnumerable<Gu
                 }
             }
 
-            await dbContext.UserBumpAccountRevisionDateByCipherIdAsync(cipher.Id, cipher.OrganizationId.GetValueOrDefault());
+            if (cipher.OrganizationId.HasValue)
+            {
+                await dbContext.UserBumpAccountRevisionDateByCipherIdAsync(cipher.Id, cipher.OrganizationId);
```
Comment (justindbaur) [inline src/Infrastructure.EntityFramework/Repositories/CipherRepository.cs:589]: And here `.Value`

**Review by justindbaur — CHANGES_REQUESTED** [review]
Very good catch, I think it's worth making a couple more changes to hopefully make this mistake harder to make in the future.

**Comment by M1cha** [comment]
@justindbaur Thanks for the review. I've addressed all of your suggestions.

**Comment by justindbaur** [comment]
Ran the code through CI manually [here](https://github.com/bitwarden/server/actions/runs/4075118330) & [here](https://github.com/bitwarden/server/actions/runs/4075118329) and it looks great, so I am going to merge this. Thank you so much for the fix!

**Review by justindbaur — APPROVED** [review]
